apiVersion: v1
kind: Secret
metadata:
  name: hana-db-secret
type: Opaque
stringData:
  DATABASE_URL: hana+hdbcli://DBADMIN:Baveshking2005%40@8b628b1e-65ac-4a57-a5c8-acd0ce20803f.hana.prod-ap21.hanacloud.ondemand.com:443/?encrypt=true&sslValidateCertificate=false